In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
df=pd.read_csv(r"C:\Kanishka\My Programs\Python\MACHINE LEARNING\CSV FILES\Housing.csv")
df.tail()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
540  1820000  3000         2          1        1      yes        no      yes   
541  1767150  2400         3          1        1       no        no       no   
542  1750000  3620         2          1        1      yes        no       no   
543  1750000  2910         3          1        1       no        no       no   
544  1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished

In [12]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
df["mainroad"]=oe.fit_transform(df[["mainroad"]])
df["basement"]=oe.fit_transform(df[["basement"]])
df["guestroom"]=oe.fit_transform(df[["guestroom"]])
df["hotwaterheating"]=oe.fit_transform(df[["hotwaterheating"]])
df["airconditioning"]=oe.fit_transform(df[["airconditioning"]])
df[["prefarea"]]=oe.fit_transform(df[["prefarea"]])


In [13]:
X=df.iloc[:,1:-1].values
y=df.iloc[:,-1].values

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[-1])],remainder="passthrough")
y= ct.fit_transform(df)
print(y)

[[1. 0. 0. ... 1. 2. 1.]
 [1. 0. 0. ... 1. 3. 0.]
 [0. 1. 0. ... 0. 2. 1.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor(random_state=0)
regressor.fit(X_train,y_train)

DecisionTreeRegressor(random_state=0)

In [17]:
y_pred=regressor.predict(X_test)

In [18]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.06280773417231607